### ISSUE TITLE
Prisma depends on Chroma

### ISSUE THREAD

**Issue by FroggiesareFluffy** [haruphoenix/elementum#4]
Since Prisma needs to call Chroma functions in drawing routines and such, either Chroma needs to be linked into Prisma, or Chroma needs to be made into a shared library rather than a static library. Without that, Prisma will compile, but cannot be used without linker errors.

**Comment by haruphoenix** [comment]
Sorry to leave you hanging - Been a bit busy. The linker errors are because the libraries are being linked in the wrong order. E.g. In the makefile

LINK_ITEMS = -lAqua -lLumina -lChroma -lPrisma -lSDL2 -lGL -lGLU -lGLEW -lSDL2_image

should be

LINK_ITEMS = -lPrisma -lAqua -lLumina -lChroma -lSDL2 -lGL -lGLU -lGLEW -lSDL2_image

The dependencies should be to the right. (Sorry, my bad)

I've made several changes to the model etc, but it's still kind of in a messy state.

I could either: A: submit those changes anyway and have you help me clean it up
or B: Wait until it's a little prettier before submitting them.

What would you prefer?
